import telebot
import os

BOT_TOKEN = os.getenv("BOT_TOKEN")

bot = telebot.TeleBot(BOT_TOKEN)

# Start command
@bot.message_handler(commands=['start'])
def send_welcome(message):
    welcome_text = """
👋 Welcome to AI Resume Bot (Free Version)

Please send your details in this format:

Name: 
Role: 
Experience: 
Skills: 
Education: 
Phone: 
Email:
"""
    bot.reply_to(message, welcome_text)


# Resume generator
@bot.message_handler(func=lambda message: True)
def generate_resume(message):
    try:
        lines = message.text.split("\n")

        data = {}
        for line in lines:
            if ":" in line:
                key, value = line.split(":", 1)
                data[key.strip().lower()] = value.strip()

        name = data.get("name", "Your Name")
        role = data.get("role", "Your Role")
        experience = data.get("experience", "Your Experience")
        skills = data.get("skills", "Your Skills")
        education = data.get("education", "Your Education")
        phone = data.get("phone", "Your Phone")
        email = data.get("email", "Your Email")

        resume = f"""
==============================
        {name.upper()}
==============================

📌 Role:
{role}

📞 Contact:
Phone: {phone}
Email: {email}

💼 Professional Summary:
Experienced {role} with {experience} of experience. Skilled in {skills}.

🛠 Skills:
{skills}

🎓 Education:
{education}

==============================
Generated by Resume Bot
"""

        bot.reply_to(message, resume)

    except Exception as e:
        bot.reply_to(message, "❌ Please follow the correct format.")

bot.polling()
